### ISSUE TITLE
The title of PDF page is the pdf's title (as opposed to paper title)

### ISSUE THREAD

**Issue by alicanb** [j3soon/arxiv-utils#1]
For example, page title for pdf of https://arxiv.org/abs/1906.07413 is "Sharelatex Example" instead of "Learning Imbalanced Datasets with Label-Distribution-Aware Margin Loss"

**Comment by j3soon** [comment]
Thank you for reporting the issue.
I think this issue is because of "Sharelatex Example" is the file name of that PDF file, so the tab renaming is overridden by the file name. It should be fixed in the newest 1.5 release.
