### ISSUE TITLE
Feature request: pdf links to abs

### ISSUE THREAD

**Issue by j-cb** [j3soon/arxiv-utils#11]
Thanks a lot for the great plugin!

Would it be possible to have a direct way to get from an arxiv.org/pdf/... hyperlink to to the abs page?

Right now (on firefox) I have to
1. left click the link,
2. select 'cancel' in the download dialog,
3. click the arxiv-utils browser button to get to the abs page,
(4. select the added 'Direct Download' link.)

The following solutions would be improvements; the first one or being able to choose one in the extension's preferences would be best in my opinion:
1. standard arxiv pdf links directly lead to the abs page on left click,
2. right click on standard arxiv pdf links offers option to go to abs page,
(3.  standard arxiv pdf links lead to download with the paper's title as filename (like the arxiv-utils 'Direct Download' link on the abs page.)

**Comment by j3soon** [comment]
In a PDF page, you should be able to get back to Abstract page by clicking the arxiv-utils button:

![image](https://user-images.githubusercontent.com/20457146/189936380-a62f3843-86aa-44e1-9de1-30311fcffb28.png)

Please refer to the third screenshot in README: https://github.com/j3soon/arxiv-utils#screenshots

**Comment by j-cb** [comment]
Yes, this is what I was referring to in the description of how it needs to be done right now.

It would be nice to be able to get to the Abstract page directly from a pdf link, without needing to open the link and deal with the download dialog first.

**Comment by j3soon** [comment]
I don't think you need to cancel the download dialog. Did you accidentally changed the behavior of opening PDFs?

The correct setting should be set as follows:

![image](https://user-images.githubusercontent.com/20457146/189938904-f023f131-4807-4aac-857d-d06bc87d53f8.png)

If you have the same settings as above. You can open a PDF link in a new page, click the arxiv-utils button, and close the original PDF page. (The firefox version should work exactly as the chrome version)

**Comment by j3soon** [comment]
Regarding your proposed solution, they can indeed save a few mouse clicks. However, all of them seem too intrusive to me: they change the default behavior without the user's intervention.

Fortunately, there is a plugin that implements solution-1: https://github.com/imurray/redirectify

[redirectify](https://github.com/imurray/redirectify) seems to work well on Chrome even when arxiv-utils is installed. But I haven't done a thorough test on it yet.

**Comment by j-cb** [comment]
Thanks a lot, the redirectify functionality is exactly what I was looking for and solves the issue for me!

It works for my Firefox together with arxiv-utils as well.

Regarding the dialog setting, I prefer the setting where pdf's don't get loaded in the browser automatically, but since this is not standard I see that there might be less of an issue for other people.

**Comment by j3soon** [comment]
Great! Good to know that [redirectify](https://github.com/imurray/redirectify) also works well with arxiv-utils on Firefox.

I think others may want the same functionality. Maybe I should add a section about using arxiv-utils with [redirectify](https://github.com/imurray/redirectify) in the README. 🙂
