### ISSUE TITLE
Migrate from Manifest V2 to Manifest V3 (for Chrome and Edge)

### ISSUE THREAD

**Issue by j3soon** [j3soon/arxiv-utils#16]
See https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/

Migration guides:
- https://developer.chrome.com/docs/extensions/mv3/mv3-migration/
- https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/

**Comment by j3soon** [comment]
Fixed in #19

**Comment by j3soon** [comment]
Chrome/Edge requires Manifest v3 now. However, Firefox does not work well with Manifest v3 due to:
1. Does not work with earlier versions of Firefox, and cannot provide fallback to Manifest v2 ([source](https://extensionworkshop.com/documentation/publish/distribute-manifest-versions/))
2. Requires manual opt-in permissions after installation ([source](https://blog.mozilla.org/addons/2022/11/17/unified-extensions-button-and-how-to-handle-permissions-in-manifest-v3/))

Therefore, we should rollback to Manifest v2 for Firefox for now.

**Comment by cipri-tom** [comment]
> Does not work with earlier versions of Firefox, and cannot provide fallback to Manifest v2 ([source](https://extensionworkshop.com/documentation/publish/distribute-manifest-versions/))

According to this link, it seems that MV2-only firefox is no longer supported since September. So it would probably be safe to transition now ?
