### ISSUE TITLE
Viewer doesn't let you go back after following an internal link

### ISSUE THREAD

**Issue by damaru2** [j3soon/arxiv-utils#23]
In firefox, the viewer that is used by the addon doesn't let you go back after following an internal link. And the addon doesn't let you write a blank prefix for the viewer either. I'd like to keep using the default viewer as that one lets you do Alt+Left and Alt+Right to navigate back and forward to the places where you jump after clicking on internal links. The viewer used by default by the addon just doesn't work for this

**Comment by j3soon** [comment]
Agree that we should allow users to disable PDF redirection in Firefox, as the default behavior is pretty intrusive.

However, disabling PDF redirection will disallow renaming for PDF tabs. See [Firefox Bug 1454760](https://bugzilla.mozilla.org/show_bug.cgi?id=1454760).

**Comment by j3soon** [comment]
I just added an option for disabling PDF redirection in [54ec5df](https://github.com/j3soon/arxiv-utils/commit/54ec5df8afd251359b387faca936efd9cd4593e4). You can try it out by [downloading the latest commit](https://github.com/j3soon/arxiv-utils/archive/refs/heads/master.zip) and install with [temporary installation](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/). Please tell me if you encountered any issue.

This option will be included in the next release.

**Comment by cipri-tom** [comment]
@damaru2  have you tried the experimental feature for firefox that lets you use it with an external viewer ? That should enable using back/forward between internal links
