### ISSUE TITLE
Add keyboard shortcut for the extension

### ISSUE THREAD

**Issue by ngntrgduc** [j3soon/arxiv-utils#24]
What do you think about adding a keyboard shortcut for the extension, like `Alt` + `A` ? Because I think toggle the extension using a keyboard shortcut is faster than clicking on the extension icon.

**Comment by j3soon** [comment]
This sounds useful, but I don't think I'll have time to implement this in the near future.

You can take a look at the following reference if you want to implement it yourself:

https://developer.chrome.com/docs/extensions/reference/commands/
