### ISSUE TITLE
Extension Failure due to arXiv PDF Page Redirection

### ISSUE THREAD

**Issue by huchinlp** [j3soon/arxiv-utils#29]
Hi, the arXiv PDF page is being redirected to browse.arxiv.org, as a result, the extension is not working. Could you please fix this issue? Thank you.

**Comment by j3soon** [comment]
Hi,

To fix this issue, I will need more context. What browser do you use? And what are the steps to reproduce this issue?

Thanks.

**Comment by xingchensong** [comment]
![image](https://github.com/j3soon/arxiv-utils/assets/13466943/b34be8ad-67d8-42ce-9db3-855e2fecb71f)
also meet this issue

**Comment by j3soon** [comment]
Hi,

I can reproduce the issue, thanks for the context!

This issue is due to a change of the arXiv website behavior. I'll need some time to investigate the new behavior and modify the extension accordingly. Thanks!

**Comment by alphanumeric-characters-and-hyphens** [comment]
When I click "Direct Download" on Firefox, nothing happens anymore. I tried with a new Firefox profile, and I tried removing and re-adding the extension. I also tried disabling redirection (which I prefer anyway), and still nothing happens when I click "Direct Download".

**Comment by j3soon** [comment]
Hi @alphanumeric-characters-and-hyphens,

The implementation of `Direct Download` has been optimized in the latest version. I just verified it functions normally on a fresh Firefox install. Could you double-check if the PDF file exists in your downloads folder?

If possible, it would be beneficial if you could record your screen while reproducing the issue.

Thanks!

**Comment by alphanumeric-characters-and-hyphens** [comment]
It's not in my downloads folder. I also tried updating (and restarting) Firefox to its latest version, and then using another new profile with a fresh install of arxiv-utils. Still nothing happens. I'm on macOS. Here's a recording:


https://github.com/j3soon/arxiv-utils/assets/96320771/b60968fc-571f-4d73-bafe-17fa5723220d

(I've also tried hard refresh of the arxiv page, and opening a new tab of the arxiv paper just in case. Still nothing.)

**Comment by j3soon** [comment]
Hi @alphanumeric-characters-and-hyphens,

Thank you for the detailed description. Previously, I only verified the direct download feature on Windows and Linux. I have just tested it on macOS Ventura (with Firefox fresh install), but still couldn't reproduce the issue.

However, I suspect there might exist a bug in the Firefox implementation, and pushed a potential fix. Could you try debug the latest commit by following [the steps here](https://github.com/j3soon/arxiv-utils#development)?

If the error still persists in the latest commit, I would need the error messages to identify the cause of this issue. Can you take a screenshot of the Developer Console (`Right Click > Inspect > Console`) right after clicking the `Direct Download` link?

If there is no errors in the Developer Console, it would be beneficial to inspect the background script logs following [the steps here](https://github.com/j3soon/arxiv-utils#development), and also take a screenshot for me.

Thank you!

**Comment by alphanumeric-characters-and-hyphens** [comment]
In my normal Firefox profile, the latest AMO release works for downloading the RAdam paper, but not Adam. The same holds for my new Firefox profile with both the latest AMO release and your latest commit. (My guess of course is that the latest commit would behave the same with my normal Firefox profile.)

Error is:

> [arXiv-utils] Sending download message to download: Adam: A Method for Stochastic Optimization, Diederik P. Kingma et al., 2014, v9.pdf from https://arxiv.org/pdf/1412.6980.pdf. [content.js:109:13](moz-extension://e5604721-65fb-4874-b631-bd8a3917fb50/content.js)
Error: filename must not contain illegal characters

**Comment by alphanumeric-characters-and-hyphens** [comment]
Yeah, I tried about 10 other papers with and without colons in the title, and that 100% correlates with failure or success.

**Comment by xingchensong** [comment]
> When I click "Direct Download" on Firefox, nothing happens anymore. 

chrome also meet this issue

**Comment by xingchensong** [comment]
https://github.com/j3soon/arxiv-utils/assets/13466943/bf0643c2-09c8-4a58-9519-e29d44954acc

**Comment by j3soon** [comment]
Hi @alphanumeric-characters-and-hyphens and @xingchensong,

Thank you for providing the detailed debugging information. I overlooked the potential connection between the issue and the paper titles. I can confirm that the issue is indeed caused by special characters (e.g., colon) in the file name.

I just pushed a hotfix. Please try out the latest commit, or simply wait for the v1.8.2 release on the extension sites.

**Comment by alphanumeric-characters-and-hyphens** [comment]
It works. Thank you!
