### ISSUE TITLE
Browser button not available on Firefox

### ISSUE THREAD

**Issue by cipri-tom** [j3soon/arxiv-utils#30]
Hello,

I've noticed that the extension button is not available on Firefox. It's never shown. 
I tried to debug, and it seems that `background.js` is never run. Could it be due to Manifest v2 ?

Thanks !

---

P.S. This little utility you've made seems to be taking a lot of fixing. Let us know if we can help

**Comment by j3soon** [comment]
Hi,

I'm unable to reproduce this issue. What's your Firefox version? I've tested on Windows 11 Firefox Nightly 121.0a1 (2023-11-07) (64-bit), and it appears that the button is functioning as expected.

Thanks for your willingness to help. :)

**Comment by cipri-tom** [comment]
Turns out it was hidden in the extension overflow button 🤦 . Sorry for the noise, I was looking in the ">>" button next to it.

I had tried debugging the code and uncommented the logging for `Enabled browser action for tab ${tabId} with url: ${url}.` . Nothing was logged, so I assumed it's not working

Thank you, again !
![Screenshot 2023-11-09 at 16 42 42](https://github.com/j3soon/arxiv-utils/assets/2991890/b77df9a5-80d4-4779-9f1d-38182db63b4f)

**Comment by j3soon** [comment]
No problem, thank you.
