### ISSUE TITLE
"A direct download link... " not work on macos chrome

### ISSUE THREAD

**Issue by MingkaiSheng** [j3soon/arxiv-utils#34]
This function： "A direct download link is added to download PDF with paper's title as the filename!"  doesn't seem to work on chrome on MacOs

![1704269669624](https://github.com/j3soon/arxiv-utils/assets/135809414/155eebb4-1e89-4a31-81e5-4ed308a55370)

**Comment by j3soon** [comment]
I need more context for resolving the issue. Could you try the following?

- Reproduce the issue in a new browser profile with no other extensions installed, so as to prevent extensions from interfering with each other.
- Take a screenshot of the Developer Console (`Right Click > Inspect > Console`) right after reproducing the bug.
- If there are no errors in the Developer Console, it would be beneficial to inspect the background script logs following [the steps here](https://github.com/j3soon/arxiv-utils#development), and also take a screenshot of the errors.

**Comment by MingkaiSheng** [comment]
> I need more context for resolving the issue. Could you try the following?
> 
> * Reproduce the issue in a new browser profile with no other extensions installed, so as to prevent extensions from interfering with each other.
> * Take a screenshot of the Developer Console (`Right Click > Inspect > Console`) right after reproducing the bug.
> * If there are no errors in the Developer Console, it would be beneficial to inspect the background script logs following [the steps here](https://github.com/j3soon/arxiv-utils#development), and also take a screenshot of the errors.

I found the cause of this problem. There is a conflict between “AIX智能下载器(图片/视频/音乐/文档)” （ID：ibdfeimkglcmdejppabkaidpippniiob） and plug-in arxiv-utils 1.8.2. Enabling “AIX..." will cause arxiv-utils to fail to change its name.

<img width="809" alt="image" src="https://github.com/j3soon/arxiv-utils/assets/135809414/5ae47273-3d39-4f97-af64-e5e15e4bc242">

**Comment by j3soon** [comment]
This is same as issue #33. I wonder if it's possible to make the `AIX ...` plugin automatically disable itself when the user is on arxiv sites.
