### ISSUE TITLE
Compatibility with Zotero connector addon

### ISSUE THREAD

**Issue by ubless607** [j3soon/arxiv-utils#44]
**Describe the bug**
When I click the button "save to Zotero" with Zotero connector Firefox addon, it doesn't work.

**To Reproduce**
1. Go to arxiv pdf page.
2. Click on save to Zotero toolbar button

**Expected behavior**
It has to be redirected and saved to Zotero Desktop.

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Browser Firefox 127.0
 - Version arxiv-utils 1.8.4

**Comment by j3soon** [comment]
Try disable `Enable PDF redirection` and click `Update`. After that, Zotero toolbar button should work on arXiv PDF pages.

![image](https://github.com/user-attachments/assets/26436306-f47a-4012-b9b6-d7b2bd39ce03)
