### ISSUE TITLE
PDF Extension Not Preserved When Saving Files

### ISSUE THREAD

**Issue by ubless607** [j3soon/arxiv-utils#49]
**Describe the bug**
The PDF extension is not retained when saving files. Instead, the file is saved in an incorrect format, such as 2210.02976.

**To Reproduce**
1. Go to https://arxiv.org/pdf/2210.09276.pdf
2. Click on 'Save file'
3. See error

**Expected behavior**
The file should be saved as 2210.02976.pdf.

**Screenshots**
![image](https://github.com/user-attachments/assets/e9de618e-fba1-4bb4-b740-9a76fad93f29)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 129.0.2

**Comment by j3soon** [comment]
Hi, I cannot reproduce this issue on Windows 11 Firefox. Are you using other extensions? I suspect this issue may be caused by other extensions.
