### ISSUE TITLE
Arxiv pages not loading on FireFox 86.0

### ISSUE THREAD

**Issue by therooler** [j3soon/arxiv-utils#5]
Hi, 

I really love this add-on, but unfortunately arxiv pages are no longer loading for me on FireFox 86.0. When I downgrade to 85.0.2 everything works correctly again. 

I know very little about Javascript or how browsers work, but when I press F12, I get the following:

Works fine:
**0.85.0.2**
```
[arXiv-utils] Retrieving title through ArXiv API request... pdfviewer.js:19:11
[arXiv-utils] Injecting PDF: https://arxiv.org/pdf/2011.01277.pdf pdfviewer.js:52:11
PDF c0fd665b66572ff7d2f6a12502d83637 [1.5 pdfTeX-1.40.21 / LaTeX with hyperref] (PDF.js: 2.7.345)
```

Does not load (white page):
**0.86**
```
[arXiv-utils] Retrieving title through ArXiv API request... pdfviewer.js:19:11
[arXiv-utils] Injecting PDF: https://arxiv.org/pdf/2008.02941.pdf pdfviewer.js:52:11
Content Security Policy: The page’s settings blocked the loading of a resource at https://arxiv.org/pdf/2008.02941.pdf (“object-src”).
Cookie “arxiv_bibex” will be soon treated as cross-site cookie against “https://export.arxiv.org/api/query?id_list=2008.02941” because the scheme does not match.
```
The third line is in red and says error, whereas the 4th line is a warning. 

Any idea on what might be wrong? I'm on Ubuntu 16.04.

**Comment by j3soon** [comment]
Thanks for providing the firefox version and the detailed logs!
Based on your report, I fixed the issue and updated the firefox version addon. You can re-download the extension and try it out. (or you can wait for the auto-update) Please tell me if there is any further issue.

**Comment by therooler** [comment]
Thanks for the quick fix, everything seems to work again!
