### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by htsenyasa** [j3soon/arxiv-utils#6]
Is it possible to add a naming convention option? "Article Title Author 1 Year" is the default one, however an option of Pascal case naming convention i.e., "ArticleTitleAuthor1Year" would be very good. Thanks in advance.

**Comment by j3soon** [comment]
Yes, I think it's possible. I'll start working on it recently.

**Comment by j3soon** [comment]
The feature is implemented in v1.6.0. The instructions are showed in the README screenshots.

arxiv-utils on Firefox has already been updated to v1.6.0, while arxiv-utils on Chrome and Edge are still under review.
